In [2]:
import numpy as np

1. Create a NumPy array 'arr' of integers from 0 to 5 and print its data type.

In [ ]:
b =[0,1,2,3,4,5]

arr = np.array(b)

arr.dtype

dtype('int64')

 Given a NumPy array 'arr', check if its data type is float64.

In [ ]:
#given
arr = np.array([1.5,2.6,3.7])
arr.dtype == np.float64

True

3. Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers

In [ ]:
arr = np.array([1+2j,3+4j,5+6j])
arr.dtype

dtype('complex128')

4. Convert an existing NumPy array 'arr' of integers to float32 data typ

In [ ]:
arr = np.array([1,2,3,4,5])
arr = arr.astype(np.float32)
arr.dtype

dtype('float32')

5. Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision

In [ ]:
arr1 =np.array([22.65,33.478,55.7411])
arr1=arr1.astype(np.float32)
arr1

array([22.65  , 33.478 , 55.7411], dtype=float32)

6. Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data
type

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
def array_attributes(arr):
    shape = arr.shape
    size = arr.size
    dtype = arr.dtype
    return shape,size,dtype

array_attributes(arr)

((2, 3), 6, dtype('int64'))

7. Create a function array_dimension that takes a NumPy array as input and returns its dimensionality

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
def array_dimension(arr):
  dimension = arr.ndim
  return dimension

array_dimension(arr)

2

8. Design a function item_size_info that takes a NumPy array as input and returns the item size and the total
size in bytes

In [ ]:
arr = np.array([[98,88,78],[68,58,48]])
def item_size_info(arr):
  item_size = arr.itemsize
  total_size = arr.nbytes
  return item_size,total_size

item_size_info(arr)

(8, 48)

9. Create a function array_strides that takes a NumPy array as input and returns the strides of the array

In [ ]:
arr = np.array([[21,22,23,24],[25,26,27,28]])
def array_strides(arr):
  strides = arr.strides
  return strides

array_strides(arr)

10. Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape
and strides of the array.

In [ ]:
def shape_stride_relationship(arr):
  shape =arr.shape
  strides = arr.strides
  return shape,strides

shape_stride_relationship(arr)

((2, 4), (32, 8))

11. Create a function `create_zeros_array` that takes an integer `n` as input and returns a NumPy array of
zeros with `n` elements

In [ ]:
def create_zeros_array(n):
  zeros = np.zeros(n)
  return zeros

create_zeros_array(6)

array([0., 0., 0., 0., 0., 0.])

12. Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs and generates a 2D
NumPy array filled with ones of size `rows x cols`.

In [ ]:
def create_ones_matrix(m,n):
  ones = np.ones((m,n))
  return ones

create_ones_matrix(3,5)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

13. Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and
creates a NumPy array with a range starting from `start`, ending at stop (exclusive), and with the specified
`step`.

In [ ]:
def generate_range_array(n,m,o):
  arr = np.arange(n,m,o)
  return arr

generate_range_array(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

14. Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as
arguments and generates a NumPy array with num equally spaced values between `start` and `stop`
(inclusive).

In [ ]:
def generate_linear_space(n,m,o):
  arr = np.linspace(n,m,o)
  return arr

generate_linear_space(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

15. Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square
identity matrix of size `n x n` using `numpy.eye`

In [ ]:
def create_identity_matrix(n):
  arr= np.eye(n)
  return arr

create_identity_matrix(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

16. Write a function that takes a Python list and converts it into a NumPy array

In [ ]:
lists =[22.5,33.5,44.5]
def list_to_array(lists):
  arr = np.array(lists)
  return arr

list_to_array(lists)

array([22.5, 33.5, 44.5])

17. Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the
same data.

In [ ]:
arr = np.array([9,5,1])
arr_view = arr.view()
arr_view[0] = 3
arr_view

array([3, 5, 1])

18. Write a function that takes two NumPy arrays and concatenates them along a specified axis.

In [ ]:
#create 2 numpy array
arr = np.array([1,2,3])
arr1 = np.array([6,5,4])
#write the function to concatenats
def concat_array(arr,arr1):
  concat = np.concatenate((arr,arr1))
  return concat

concat_array(arr,arr1)


array([1, 2, 3, 6, 5, 4])

19. Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy.concatenate`.

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
arr1 = np.array([[7,8,9,13],[10,11,12,14]])

def concat_array(arr,arr1):
  concat = np.concatenate((arr,arr1),axis=1)
  return concat

concat_array(arr,arr1)

array([[ 1,  2,  3,  7,  8,  9, 13],
       [ 4,  5,  6, 10, 11, 12, 14]])

20. Write a function that vertically stacks multiple NumPy arrays given as a list

In [ ]:
lists = [np.array([1,2,3]),np.array([4,5,6]),np.array([7,8,9])]
def stack_array(lists):
  stack = np.vstack(lists)
  return stack

stack_array(lists)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

21. Write a Python function using NumPy to create an array of integers within a specified range (inclusive) with a given step size.

In [ ]:
def create_array(n,m,o):
  arr =np.arange(n,m,o)
  return arr

create_array(0,10,2)

array([0, 2, 4, 6, 8])

 22. Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1
(inclusive).

In [ ]:
def create_array(n):
  arr = np.linspace(0,1,n)
  return arr

create_array(10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

23. Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and
1000 (inclusive)

In [ ]:
def create_log_array(n):
  arr = np.logspace(1,1000,n)
  return arr

create_log_array(5)

/usr/local/lib/python3.10/dist-packages/numpy/core/function_base.py:298: RuntimeWarning: overflow encountered in power
  return _nx.power(base, y)


array([1.00000000e+001, 5.62341325e+250,             inf,             inf,
                   inf])

24. Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values
are random integers between 1 and 100.

In [ ]:
import pandas as pd

In [ ]:
arr =np.random.randint(1,100,(5,3))
df = pd.DataFrame(arr)
df

0   1   2
0  18  26  42
1  28  36   7
2  76  25  53
3  85  84  59
4  72  42  44

25. Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column
with zeros. Use NumPy operations within the Pandas DataFrame

In [ ]:
def replace(df):
  df[df<0]=0
  return df

df = pd.DataFrame([[1,-2,3],[-4,5,-6],[7,-8,9]])
replace(df)

0  1  2
0  1  0  3
1  0  5  0
2  7  0  9

26. Access the 3rd element from the given NumPy array.

In [ ]:
arr = np.array([10,20,30,40,50])
arr[2]

30

27. Retrieve the element at index (1, 2) from the 2D NumPy array

In [ ]:
arr_2d = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
arr_2d[1,2]

6

28. Using boolean indexing, extract elements greater than 5 from the given NumPy array.

In [ ]:
arr = np.array([3, 8, 2, 10, 5, 7]) >5
arr

array([False,  True, False,  True, False,  True])

29. Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[2:6]

array([3, 4, 5, 6])

 30. Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array.

In [ ]:
arr_2d = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
arr_2d[0:2,1:3]


array([[2, 3],
       [5, 6]])

31.Write a NumPy function to extract elements in specific order from a given 2D array based on indices
provided in another array.

In [ ]:
arr = np.array([[3,2,1],[6,5,4],[9,8,7]])
indices = np.array([[0,1],[1,2]])
arr[indices]

array([[[3, 2, 1],
        [6, 5, 4]],

       [[6, 5, 4],
        [9, 8, 7]]])

32. Create a NumPy function that filters elements greater than a threshold from a given 1D array using
boolean indexing.

In [ ]:
arr = np.array([3, 8, 2, 10, 5, 7])
threshold = 5
arr>threshold

array([False,  True, False,  True, False,  True])

33. Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three
separate arrays for each dimension.

In [ ]:
arr_3d = np.array([[[1, 2, 3],[4, 5, 6]],[[7, 8, 9],[10, 11, 12]]])
indices_0 = np.array([0, 1])
indices_1 = np.array([0, 1])
indices_2 = np.array([0, 1])
arr_3d[indices_0,indices_1,indices_2]

array([ 1, 11])

34. Write a NumPy function that returns elements from an array where both two conditions are satisfied
using boolean indexing

In [ ]:
arr =np.array([9,8,6,5,3,2])
condition1 = arr>5
condition2 = arr%2==0
arr[condition1 & condition2]

array([8, 6])

35. Create a NumPy function that extracts elements from a 2D array using row and column indices provided
in separate arrays.

In [ ]:
arr_2d = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
row_indices = np.array([0, 1])
col_indices = np.array([1, 2])
arr_2d[row_indices,col_indices]

array([2, 6])

36. Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting

In [ ]:
arr = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
scalar = 5
arr + scalar

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

37. Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the
corresponding element in arr1 using NumPy broadcasting

In [ ]:
arr1 = np.array([[1, 2, 3]])
arr2 = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
arr = np.reshape(arr1,(3,1))
arr * arr2


array([[ 1,  2,  3,  4],
       [10, 12, 14, 16],
       [27, 30, 33, 36]])

38. Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using
NumPy broadcasting.

In [ ]:
arr1 = np.array([[1, 2, 3, 4]])
arr2 = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9],[10, 11, 12]])
arr = np.reshape(arr1,(4,1))
arr + arr2

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12],
       [14, 15, 16]])

39. Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy
broadcasting

In [ ]:
arr1 = np.array([[1],[2],[3]])
arr2 = np.array([[1, 2, 3]])
arr1 + arr2

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

40. Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy
broadcasting. Handle the shape incompatibility

In [ ]:
arr1 = np.array([[1, 2, 3],[4, 5, 6]])
arr2 = np.array([[1, 2],[3, 4]])
arr = np.reshape(arr1,(2,3,1))



41. Calculate column wise mean for the given array:

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
np.mean(arr,axis=0)

array([2.5, 3.5, 4.5])

42. Find maximum value in each row of the given array:

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
np.max(arr,axis =1)

array([3, 6])

43. For the given array, find indices of maximum value in each column

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
np.argmax(arr,axis=0)

array([1, 1, 1])

44. For the given array, apply custom function to calculate moving sum along rows.

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
np.cumsum(arr,axis = 1)

array([[ 1,  3,  6],
       [ 4,  9, 15]])

45. In the given array, check if all elements in each column are even

In [ ]:
arr = np.array([[2, 4, 6], [3, 5, 7]])
arr%2==0

array([[ True,  True,  True],
       [False, False, False]])

46. Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns. Return the
reshaped matrix

In [ ]:
original_array = np.array([1, 2, 3, 4, 5, 6])
m = 2
n = 3
arr.reshape(m,n)

array([[1, 2, 3],
       [4, 5, 6]])

47. Create a function that takes a matrix as input and returns the flattened array.

In [ ]:
input_matrix = np.array([[1, 2, 3], [4, 5, 6]])
def flatten_matrix(input_matrix):
  flatten_array = input_matrix.flatten()
  return flatten_array

flatten_matrix(input_matrix)

array([1, 2, 3, 4, 5, 6])

48. Write a function that concatenates two given arrays along a specified axis.

In [ ]:
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

def concat_array(array1,array2):
  add_array = np.concatenate((array1,array2),axis=1)
  return(add_array)
concat_array(array1,array2)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

49. Create a function that splits an array into multiple sub-arrays along a specified axis

In [ ]:
original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
def split_array(original_array):
  sub_array = np.array_split(original_array,3)
  return sub_array

split_array(original_array)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

50. Write a function that inserts and then deletes elements from a given array at specified indices

In [ ]:
original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]


51. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10.
Perform element-wise addition between `arr1` and `arr2`.

In [3]:
arr1 = np.random.randint(1,100,10)
arr2 = np.arange(1,11)
arr1 + arr2

array([44, 70, 87, 29, 17, 28, 62, 92, 63, 83])

52. Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integers
from 1 to 10. Subtract `arr2` from `arr1` element-wise.

In [4]:
arr1 = np.arange(10,0,-1)
arr2 = np.arange(1,11)
arr1 - arr2

array([ 9,  7,  5,  3,  1, -1, -3, -5, -7, -9])

53. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 5.
Perform element-wise multiplication between `arr1` and `arr2`.

In [6]:
arr1 = np.random.randint(1,100,5)
arr2 = np.arange(1,6)
arr1 * arr2


array([ 43,  56,  60, 216, 380])

54. Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1
to 5. Perform element-wise division of `arr1` by `arr2`.

In [7]:
arr1 = np.arange(2,11,2)
arr2 = np.arange(1,6)
arr1/arr2

array([2., 2., 2., 2., 2.])

55. Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers
reversed. Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wise.

In [8]:
arr1 = np.arange(1,6)
arr2 = np.flip(arr1)
arr1**arr2

array([ 1, 16, 27, 16,  5])

56. Write a function that counts the occurrences of a specific substring within a NumPy array of strings.

57. Write a function that extracts uppercase characters from a NumPy array of strings.

arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])

In [9]:
arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])
def extract_uppercase(arr):
  uppercase = np.char.upper(arr)
  return uppercase

extract_uppercase(arr)

array(['HELLO', 'WORLD', 'OPENAI', 'GPT'], dtype='<U6')

58. Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string.

In [10]:
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
def replace_substring(arr):
  new_string = np.char.replace(arr,'apple','kiwi')
  return new_string

replace_substring(arr)

array(['kiwi', 'banana', 'grape', 'pinekiwi'], dtype='<U8')

59. Write a function that concatenates strings in a NumPy array element-wise.

In [11]:
arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])

def concat_string(arr1,arr2):
  concat = np.char.add(arr1,arr2)
  return concat

concat_string(arr1,arr2)

array(['HelloOpen', 'WorldAI'], dtype='<U9')

60. Write a function that finds the length of the longest string in a NumPy array.

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

In [12]:
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
def find_length(arr):
  length = np.char.str_len(arr)
  return length

find_length(arr)

array([5, 6, 5, 9])

61. Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and
standard deviation of the dataset using NumPy's functions

In [14]:
arr = np.random.randint(1,1000,100)
print('Mean =',np.mean(arr))
print('Median =',np.median(arr))
print('Var =',np.var(arr))
print('std =',np.std(arr))

Mean = 496.64
Median = 465.5
Var = 68008.05040000001
std = 260.7835316886402


62. Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the
dataset.

In [15]:
arr = np.random.randint(1,100,50)
print('25th percentile =',np.percentile(arr,25))
print('75th percentile =',np.percentile(arr,75))

25th percentile = 18.25
75th percentile = 74.5


63. Create two arrays representing two sets of variables. Compute the correlation coefficient between these
arrays using NumPy's `corrcoef` function.

In [16]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])
np.corrcoef(arr1,arr2)

array([[1., 1.],
       [1., 1.]])

64. Create two matrices and perform matrix multiplication using NumPy's `dot` function.

In [18]:
max1 =np.matrix([[1,2],[3,4]])
max2 = np.matrix([[5,6],[7,8]])
np.dot(max1,max2)

matrix([[19, 22],
        [43, 50]])

65. Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th
percentiles along with the first and third quartiles

In [19]:
arr =np.random.randint(10,1000,50)
print('10th percentile =',np.percentile(arr,10))
print('50th percentile =',np.percentile(arr,50))
print('90th percentile =',np.percentile(arr,90))

10th percentile = 112.9
50th percentile = 361.5
90th percentile = 896.5


66. Create a NumPy array of integers and find the index of a specific element.

In [20]:
arr = np.array([1,2,3,4,5,6,7,8,9])
np.where(arr==5)

(array([4]),)

67. Generate a random NumPy array and sort it in ascending order.

In [21]:
arr = np.random.randint(1,100,10)
np.sort(arr)

array([15, 20, 23, 31, 54, 59, 68, 87, 96, 97])

68. Filter elements >20  in the given NumPy array.

In [22]:
arr = np.array([12, 25, 6, 42, 8, 30])
arr[arr > 20]

array([25, 42, 30])

69. Filter elements which are divisible by 3 from a given NumPy array.

In [23]:
arr = np.array([1, 5, 8, 12, 15])
arr[arr%3==0]

array([12, 15])

70. Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array.

In [24]:
arr = np.array([10, 20, 30, 40, 50])
arr[(arr>=20) & (arr<=40)]

array([20, 30, 40])

71. For the given NumPy array, check its byte order using the `dtype` attribute byteorder.

In [26]:
arr = np.array([1, 2, 3])
arr.dtype.byteorder

'='

72. For the given NumPy array, perform byte swapping in place using `byteswap()`.

In [27]:
arr = np.array([1, 2, 3], dtype=np.int32)
arr.byteswap()

array([16777216, 33554432, 50331648], dtype=int32)

73. For the given NumPy array, swap its byte order without modifying the original array using
`newbyteorder()`.

In [28]:
arr = np.array([1, 2, 3], dtype=np.int32)
arr.newbyteorder()

array([16777216, 33554432, 50331648], dtype='>i4')

74. For the given NumPy array and swap its byte order conditionally based on system endianness using
`newbyteorder()`.

In [29]:
arr = np.array([1, 2, 3], dtype=np.int32)
arr.newbyteorder(arr.dtype.byteorder)

array([1, 2, 3], dtype=int32)

75. For the given NumPy array, check if byte swapping is necessary for the current system using `dtype`
attribute `byteorder`.

In [30]:
arr = np.array([1, 2, 3], dtype=np.int32)
arr.dtype.byteorder

'='

76. Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify
an element in `copy_arr`. Check if modifying `copy_arr` affects `arr1`.

In [31]:
arr1 = np.arange(1,11)
copy_arr = arr1.copy()
copy_arr[0] = 100
print(arr1)
print(copy_arr)

[ 1  2  3  4  5  6  7  8  9 10]
[100   2   3   4   5   6   7   8   9  10]


77. Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from
the matrix. Modify an element in `view_slice` and observe if it changes the original `matrix`.

In [32]:
max = np.random.randint(1,100,(3,3))
view_slice = max[0:2,0:2]
view_slice[0,0] = 100
print(max)
print(view_slice)

[[100  67  74]
 [ 94  93  10]
 [ 58   7  69]]
[[100  67]
 [ 94  93]]


78. Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice
`view_b` from `array_a` and broadcast the addition of 5 to view_b. Check if it alters the original `array_a`.

In [33]:
array_a = np.arange(1,13).reshape(4,3)
view_b = array_a[0:2,0:2]
view_b + 5

array([[ 6,  7],
       [ 9, 10]])

79. Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped view
`reshaped_view` of shape (4, 2) from orig_array. Modify an element in `reshaped_view` and check if it
reflects changes in the original `orig_array`.

In [35]:
orig_array = np.arange(1,9).reshape(2,4)
reshaped_view = orig_array.reshape(4,2)
reshaped_view[0,0] = 10
print(orig_array)
print(reshaped_view)

[[10  2  3  4]
 [ 5  6  7  8]]
[[10  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]]


80. Create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` of
elements greater than 5. Modify an element in `data_copy` and verify if it affects the original `data`.

In [36]:
data = np.random.randint(1,100,(3,4))
data_copy = data[data>5].copy()
data_copy[0] = 100
print(data)
print(data_copy)

[[26 94 28 89]
 [60 30  7 20]
 [43 11 86 94]]
[100  94  28  89  60  30   7  20  43  11  86  94]


81. Create two matrices A and B of identical shape containing integers and perform addition and subtraction
operations between them.

In [37]:
a = np.random.randint(1,100,(3,3))
b = np.random.randint(1,100,(3,3))
print(a+b)
print(a-b)

[[142 137 134]
 [ 71 128  78]
 [109 126 106]]
[[-42 -17  20]
 [ 41   2  46]
 [-71 -30  22]]


82. Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication.

In [38]:
c = np.random.randint(1,100,(3,2))
d = np.random.randint(1,100,(2,4))
np.dot(c,d)

array([[3336, 5343, 2446, 3671],
       [3104, 2945, 2426, 3241],
       [3374, 5348, 2478, 3708]])

83. Create a matrix `E` and find its transpose

In [39]:
e = np.random.randint(1,100,(3,3))
e.T

array([[53, 29, 78],
       [23, 56, 11],
       [ 8, 90, 40]])

84. Generate a square matrix `F` and compute its determinant.

In [40]:
f = np.random.randint(1,100,(3,3))
np.linalg.det(f)

137685.9999999998

85. Create a square matrix `G` and find its inverse

In [41]:
g = np.random.randint(1,100,(3,3))
np.linalg.inv(g)

array([[-0.00473464, -0.01505284,  0.0186081 ],
       [ 0.01816939,  0.00722445, -0.01725778],
       [-0.01804974,  0.02324018,  0.00836396]])